# Análise de Dados das Notas dos Enem de Pernambuco

### Disciplina: Tópicos Avançados em Gerencimento de Dados e Informações
### Alunos: Maria Teresa e Victor Amarante

## Importar bibliotecas

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

pd.set_option('display.max_columns', None)

## Importar base de dados

In [2]:
df2021 = pd.read_csv('MICRODADOS_ENEM_2021.csv', sep=';', encoding='iso-8859-1')

## Visualização da base de dados

In [3]:
df2021

,NU_INSCRICAO,NU_ANO,TP_FAIXA_ETARIA,TP_SEXO,TP_ESTADO_CIVIL,TP_COR_RACA,TP_NACIONALIDADE,TP_ST_CONCLUSAO,TP_ANO_CONCLUIU,TP_ESCOLA,TP_ENSINO,IN_TREINEIRO,CO_MUNICIPIO_ESC,NO_MUNICIPIO_ESC,CO_UF_ESC,SG_UF_ESC,TP_DEPENDENCIA_ADM_ESC,TP_LOCALIZACAO_ESC,TP_SIT_FUNC_ESC,CO_MUNICIPIO_PROVA,NO_MUNICIPIO_PROVA,CO_UF_PROVA,SG_UF_PROVA,TP_PRESENCA_CN,TP_PRESENCA_CH,TP_PRESENCA_LC,TP_PRESENCA_MT,CO_PROVA_CN,CO_PROVA_CH,CO_PROVA_LC,CO_PROVA_MT,NU_NOTA_CN,NU_NOTA_CH,NU_NOTA_LC,NU_NOTA_MT,TX_RESPOSTAS_CN,TX_RESPOSTAS_CH,TX_RESPOSTAS_LC,TX_RESPOSTAS_MT,TP_LINGUA,TX_GABARITO_CN,TX_GABARITO_CH,TX_GABARITO_LC,TX_GABARITO_MT,TP_STATUS_REDACAO,NU_NOTA_COMP1,NU_NOTA_COMP2,NU_NOTA_COMP3,NU_NOTA_COMP4,NU_NOTA_COMP5,NU_NOTA_REDACAO,Q001,Q002,Q003,Q004,Q005,Q006,Q007,Q008,Q009,Q010,Q011,Q012,Q013,Q014,Q015,Q016,Q017,Q018,Q019,Q020,Q021,Q022,Q023,Q024,Q025
0,210053865474,2021,5,F,1,1,1,1,3,1,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3144805,Nova Lima,31,MG,0,1,1,0,NaN,881.0,892.0,NaN,NaN,574.6,472.6,NaN,NaN,BBCCECEABCEABADDAAEECBEBADADAAABABBABBACCCBBB,99999BADDEAEBACADADDAEABCEECDDBBAEADEDEABADBBA...,NaN,1,NaN,BEECCAEABADBCAEBAAEEDDEBBBADBCBAAEEBBBADCCBBA,ABBACAAECACDBDDADEBDDCBDCEDBEDDBBBBDCEEAADABAC...,NaN,1.0,140.0,120.0,120.0,180.0,200.0,760.0,F,F,B,B,3.0,D,A,B,C,B,A,B,A,B,A,A,A,A,B,A,A,B,A,B,B
1,210052384164,2021,12,M,1,1,1,1,11,1,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2704302,Maceió,27,AL,1,1,1,1,912.0,882.0,891.0,901.0,505.9,551.8,498.3,461.5,DCBCCBDBCCCCCCDDCDCCCACCABCCECCCCAADCCCBBCADE,ECCDAAEBCDACBDBDECABBEAACBCBCCCDACEABEBEBACAE,99999ACECCEEBACDABACBECBBCDBDEBDDCCCDECCDDCCCC...,CDCCBCCCDCCCCBEACEECAEABECCCDCBBCABACDAEDCCEC,1,DABCEDEBEEBBCABEDDCBCBECDADCDAACBDCCCDBBBEBAB,EBAAEADBCACBBABEECBAAEEBBBADCBADBCEDDEBBCAEAB,ACABBACAEADCEADABDACDCEABDDADBEDDDEBBACCDDDCCE...,DCCAEBABDDCABEECCBCCEXADDCEECDEBADCABBDBDEDCE,1.0,120.0,120.0,120.0,120.0,80.0,560.0,B,B,B,B,3.0,B,A,B,C,A,A,B,A,A,A,A,A,A,B,A,A,C,A,A,A
2,210052589243,2021,13,F,3,1,1,1,15,1,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3515707,Ferraz de Vasconcelos,35,SP,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,B,C,C,B,3.0,C,A,B,B,A,A,B,B,A,A,B,A,A,B,A,A,C,B,B,B
3,210052128335,2021,3,M,1,3,1,2,0,2,1.0,0,2304202.0,Crato,23.0,CE,2.0,1.0,1.0,2304202,Crato,23,CE,1,1,1,1,911.0,880.0,890.0,902.0,580.7,678.9,638.9,659.5,CCABBDAEDBEBEDDCAAABBDAADBDCACACEDAABCEABAEBC,CBBDABAABBAAEECEBAADADBEBCAEEBEDDEBBBADBCBEDC,ABBCA99999CDECCCBADCDBCEAEBBAAEADEEADDACAEDDAB...,EACDCEACDDDDCBDDCABADAEBACDCDDEDBBCDBECACCCCA,0,CDBBBCABEDEDEAAEBACCCBDABCDCBCBDECDADCDBBEEBB,BBBAAEECBBABEECEBAAEADBCACAEABEDDEBBBADBCBADC,ABBCAEAACADDCACDCADABBBBDEBBACEADCEBDDACEEDDDB...,ECCCABBDBDDDCEDDCABXEEEBABEDCEDCCAEBADBCCECDA,1.0,120.0,180.0,120.0,200.0,160.0,780.0,B,B,B,B,6.0,B,A,B,C,A,A,B,A,A,A,A,A,A,B,A,A,B,A,B,B
4,210051353021,2021,2,F,1,3,1,2,0,2,1.0,0,2311603.0,Redenção,23.0,CE,2.0,1.0,1.0,2300150,Acarape,23,CE,1,1,1,1,912.0,882.0,891.0,901.0,497.7,532.4,457.6,582.6,BABCDCCBEBCD.DEDCABCBDEDAABEDADBDBCDECCAEDBCB,CAE.ACDCAAEBBEDEBCADADEDADAACEBDABBCEABBCDEAC,99999EAACBDCBECCABADBEDADCDADDCDDECABAADEBBDAC...,ACEDEBECABDABDEECBDEEADDDDBEBCEADCCADCADEDCEB,1,DABCEDEBEEBBCABEDDCBCBECDADCDAACBDCCCDBBBEBAB,EBAAEADBCACBBABEECBAAEEBBBADCBADBCEDDEBBCAEAB,ACABBACAEADCEADABDACDCEABDDADBEDDDEBBACCDDDCCE...,DCCAEBABDDCABEECCBCCEXADDCEECDEBADCABBDBDEDCE,1.0,120.0,140.0,160.0,180.0,180.0,780.0,D,E,F,D,4.0,C,A,B,C,A,A,B,A,B,A,B,A,A,B,A,B,E,A,B,B
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2685048,210052034039,2021,4,M,1,1,1,2,0,2,1.0,0,3205002.0,Serra,32.0,ES,1.0,1.0,1.0,3205002,Serra,32,ES,1,1,1,1,912.0,882.0,891.0,901.0,626.3,672.2,663.2,731.3,DABDBEEBECCADABAEDCBCDBCDABCBEACDAACCDEDDCACB,ECADAADBBDBBDABEECBAACEDBBAECBADBCEEDEBBCAEBB,ACABB99999DEEADAABADEEEDBDDADBEDDDEBDABADCDACB...,DCCAECADDDCABDECDBCBEAADACDDCDDBADBEDBBAEBDCE,0,DABCEDEBEEBBCABEDDCBCBECDADCDAACBDCCCDBBBEBAB,EBAAEADBCACBBABEECBAAEEBBBADCBADBCEDDEBBCAEAB,ACABBACAEADCEADABDACDCEABDDADBEDDDEBBACCDDDCCE...,DCCAEBABDDCABEECCBCCEXADDCEECDEBADCABBDBDEDCE,1.0,140.0,120.0,100.0,140.0,180.0,680.0,G,G,D,F,5.0,C,A,B,B,B,A,B,B,B,A,A,A,A,B,A,B,E,B,C,B
2685049,210051134913,2021,4,F,1,3,1,2,0,2,1.0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2702306,Coruripe,27,AL,1,1,1,1,909.0,881.0,892.0,899.0,535.2,461.6,510.8,599.9,BECDCDEAABCBACEDCBCABECEADEADEACDEBACBCEBDAED,CCEDCAAEBABABAEB..E.....E.A....E..EB.........,99999AAEACCDBACEDACBDABECEDBAD............D......,DEBECACDCDCADBACDCCBADAEDABCBCEDCDACBDEABECDA,1,EDECABEDABCBEBACCDCBBEEBBCBDAAECDCBDCDBBBADCD,BEECCAEABADBCAEBAAEEDDEBBBADBCBAAEEBBBADCCBBA,ABBACAAECACDBDDADEBDDCBDCEDBEDDBBBBDCEEAADABAC...,EEXEBABDDCECCBCCECDCAEBADEABBDBDEDCEDCCADDCAB,1.0,140.0,200.0,120.0,140.0,200.0,800.0,D,D,A,A,5.0,A,A,B,D,A,B,B,A,A,A,A,A,A,B,A,A,D,A,A,B
2685050,210051964252,2021,5,M,1,3,1,1,2,1,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2927408,Salvador,29,BA,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,E,F,E,E,4.0,C,A,C,D,A,A,B,B,B,B,B,B,B,B,B,B,B,B,B,B
2685051,210053743073,2021,4,F,1,0,1,1,2,1,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2211001,Teresina,22,PI,1,1,1,1,912.0,882.0,891.0,901.0,407.5,337.9,403.7,412.3,DDCCBABEECBDCDBBCECCDDACABCCEDAEEDDBBCBCDEDCD,EBBDCBCABDDACCEABEEDBCABDCADBACCDBAABCDBDCABC,EECAC99999DABEDDBAEADDDADCABDCBBDDDCADCCBCDCAD...,DECADDBCABDCBAAACEDBCDDECBDCABDBCBEBDCBABDCBA,0,DABCEDEBEEBBCABEDDCBCBECDADCDAACBDCCCDBBBEBAB,EBAAEADBCACBBABEECBAAEEBBBADCBADBCEDDEBBCAEAB,ACABBACAEADCEADABDACDCEABDDADBEDDDEBBACCDDDCCE...,DCCAEBABDDCABEECCBCCEXADDCEECDEBADCABBDBDEDCE,1.0,100.0,120.0,100.0,120.0,80.0,520.0,H,H,B,B,4.0,C,A,B,C,A,B,B,A,B,A,B,A,A,B,A,A,C,A,B,B
2685052,210053609120,2021,13,F,1,1,1,2,0,2,NaN,0,4317400.0,Santiago,43.0,RS,2.0,1.0,1.0,4317400,Santiago,43,RS,0,1,1,0,NaN,880.0,890.0,NaN,NaN,386.0,330.6,NaN,NaN,CAABADAEDCCCBABCAADEADCCCADECADCBBAADEAACADCA,99999DACECBABEDBAAEDDDEADBDCCCDCEAADBBBABDADCE...,NaN,1,NaN,BBBAAEECBBABEECEBAAEADBCACAEABEDDEBBBADBCBADC,ABBCAEAACADDCACDCADABBBBDEBBACEADCEBDDACEEDDDB...,NaN,6.0,0.0,0.0,0.0,0.0,0.0,0.0,C,C,C,B,4.0,B,A,B,C,B,A,B,A,A,A,B,A,A,B,A,A,C,A,A,B

## Filtrando a base de dados para o estado de Pernambuco

In [4]:
df_pe2021 = df2021.query('SG_UF_PROVA == "PE"')
df_pe2021

,NU_INSCRICAO,NU_ANO,TP_FAIXA_ETARIA,TP_SEXO,TP_ESTADO_CIVIL,TP_COR_RACA,TP_NACIONALIDADE,TP_ST_CONCLUSAO,TP_ANO_CONCLUIU,TP_ESCOLA,TP_ENSINO,IN_TREINEIRO,CO_MUNICIPIO_ESC,NO_MUNICIPIO_ESC,CO_UF_ESC,SG_UF_ESC,TP_DEPENDENCIA_ADM_ESC,TP_LOCALIZACAO_ESC,TP_SIT_FUNC_ESC,CO_MUNICIPIO_PROVA,NO_MUNICIPIO_PROVA,CO_UF_PROVA,SG_UF_PROVA,TP_PRESENCA_CN,TP_PRESENCA_CH,TP_PRESENCA_LC,TP_PRESENCA_MT,CO_PROVA_CN,CO_PROVA_CH,CO_PROVA_LC,CO_PROVA_MT,NU_NOTA_CN,NU_NOTA_CH,NU_NOTA_LC,NU_NOTA_MT,TX_RESPOSTAS_CN,TX_RESPOSTAS_CH,TX_RESPOSTAS_LC,TX_RESPOSTAS_MT,TP_LINGUA,TX_GABARITO_CN,TX_GABARITO_CH,TX_GABARITO_LC,TX_GABARITO_MT,TP_STATUS_REDACAO,NU_NOTA_COMP1,NU_NOTA_COMP2,NU_NOTA_COMP3,NU_NOTA_COMP4,NU_NOTA_COMP5,NU_NOTA_REDACAO,Q001,Q002,Q003,Q004,Q005,Q006,Q007,Q008,Q009,Q010,Q011,Q012,Q013,Q014,Q015,Q016,Q017,Q018,Q019,Q020,Q021,Q022,Q023,Q024,Q025
16,210053788150,2021,7,F,1,1,1,1,4,1,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2613701,São Lourenço da Mata,26,PE,1,1,1,1,911.0,880.0,890.0,902.0,487.9,419.9,488.2,553.1,CDCDDAEBDEBABECEACDAAEBAECAEADDBCDDADEAABECDA,AAAABEACBDBABEBDBEECCBACDEAEBEDABABADCDAABEEB,BCAEA99999DBEABBBACADCBEDDDBBAEADEEABAECDADACD...,DCCDBADBACECADABCDDADBEEDDBACCBCEDBACDBCCAEDE,0,CDBBBCABEDEDEAAEBACCCBDABCDCBCBDECDADCDBBEEBB,BBBAAEECBBABEECEBAAEADBCACAEABEDDEBBBADBCBADC,ABBCAEAACADDCACDCADABBBBDEBBACEADCEBDDACEEDDDB...,ECCCABBDBDDDCEDDCABXEEEBABEDCEDCCAEBADBCCECDA,1.0,140.0,120.0,140.0,160.0,160.0,720.0,E,E,D,B,2.0,B,A,B,C,B,A,B,A,B,A,A,A,A,B,A,A,C,A,A,B
19,210053797083,2021,11,M,1,3,1,1,9,1,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2613701,São Lourenço da Mata,26,PE,1,1,1,1,909.0,881.0,892.0,899.0,388.1,602.0,337.1,629.5,DCACDDACCBCEDBACADDCEACDDBBADDBBABACACCDCCBCE,BDECCCEBDCECBDECCAEDDDEBBDADBABBACBDBECDCCABA,99999BCCBCBABADCDDBCDCDEECCBBDEECCDEEECCBCCDCB...,ECDEBBDACDDCDBBCDCCDCABECDDCBDDDDCAADBCADDEAD,1,EDECABEDABCBEBACCDCBBEEBBCBDAAECDCBDCDBBBADCD,BEECCAEABADBCAEBAAEEDDEBBBADBCBAAEEBBBADCCBBA,ABBACAAECACDBDDADEBDDCBDCEDBEDDBBBBDCEEAADABAC...,EEXEBABDDCECCBCCECDCAEBADEABBDBDEDCEDCCADDCAB,1.0,140.0,200.0,140.0,180.0,200.0,860.0,E,E,B,B,2.0,C,A,B,C,A,A,B,A,B,A,A,A,A,B,B,A,B,A,A,B
50,210051819810,2021,4,F,1,3,1,1,0,1,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2615300,Timbaúba,26,PE,1,1,1,1,912.0,882.0,891.0,901.0,387.0,486.4,436.9,404.0,DCCEEDBADDCDAEEAEBEACCEDABBCBEAEEBCEADADBCECA,CCAAAACDCABCECBBEEADCEDDBDDACBCBDBDACBCECDCDA,99999EEACEDEEACBBBAADECECAEDCADBDCDDDEAEDBCBAE...,BABBCECEEBDDBEBEDBBAAABEBCDCEDBCDCBDAEACDADDB,1,DABCEDEBEEBBCABEDDCBCBECDADCDAACBDCCCDBBBEBAB,EBAAEADBCACBBABEECBAAEEBBBADCBADBCEDDEBBCAEAB,ACABBACAEADCEADABDACDCEABDDADBEDDDEBBACCDDDCCE...,DCCAEBABDDCABEECCBCCEXADDCEECDEBADCABBDBDEDCE,1.0,100.0,180.0,120.0,120.0,140.0,660.0,B,D,B,B,2.0,B,A,B,B,A,A,B,B,A,A,A,A,A,B,B,A,C,A,B,B
57,210054293853,2021,3,F,1,3,1,1,1,1,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2608750,Lagoa Grande,26,PE,1,1,1,1,910.0,879.0,889.0,900.0,507.1,472.2,474.2,506.3,BADAECADDECADBEEADBCABCDEBEBEDCBEEBEAEADBCACA,BADEDADBBBACEDAEBDEABCDBEBCDECDEABDEABCEABCAE,99999EDABAABDDEBDEBCAADBBADABDCEACBDECADBEDBCA...,DDCDDACEDCCECEBBAEDEDAADACDECEECAABCECECBACDA,1,ADCDCDBBBECDCCDCBCBDABCAADCBEBABEEBBBCABEDEDE,BADCBADBCEDDEBBADBCABEECCAEABEBAAECBBABAAEEBB,CAABBCAEAABDCDEADCEDBEDDDABBBBDEBCEADABDBACACD...,DDCABDCCAEDCEBBDBDAEEBADCAECDBCCCCDDCEEBABXEE,1.0,120.0,120.0,120.0,120.0,100.0,580.0,B,E,A,A,5.0,A,A,B,D,B,A,B,A,B,A,A,A,A,B,B,A,E,A,A,B
69,210054019198,2021,14,M,1,3,1,1,15,1,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2611606,Recife,26,PE,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,E,E,D,D,3.0,D,A,B,C,B,A,B,A,B,A,A,A,A,B,A,A,C,B,B,B
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2684951,210051146292,2021,2,F,1,1,1,1,1,1,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2607901,Jaboatão dos Guararapes,26,PE,1,1,1,1,910.0,879.0,889.0,900.0,553.6,553.8,557.7,593.5,AACACBCBDECDCEDCAECECBDBDACCBCCBECCAEDCBDCBCE,BDBCBAAABACBABBDCABAABACCAEACCADBECABABBAEECD,CAAAE99999BACDCADEDBBABDDACBCCBEBCBECCBADADADB...,DDCCEADCABCBEDCAACEACBCBCBDCABECACECADEACDCEA,0,ADCDCDBBBECDCCDCBCBDABCAADCBEBABEEBBBCABEDEDE,BADCBADBCEDDEBBADBCABEECCAEABEBAAECBBABAAEEBB,CAABBCAEAABDCDEADCEDBEDDDABBBBDEBCEADABDBACACD...,DDCABDCCAEDCEBBDBDAEEBADCAECDBCCCCDDCEEBABXEE,1.0,120.0,120.0,80.0,120.0,100.0,540.0,D,F,D,D,3.0,I,A,C,D,B,A,B,B,B,A,B,A,B,C,B,A,D,B,B,B
2684977,210053824236,2021,6,F,1,1,1,1,3,1,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2614501,Surubim,26,PE,1,1,1,1,912.0,882.0,891.0,901.0,440.2,463.7,487.6,391.1,DCEDBBDCECDADAEEEAAADECADAADBDDBDACEEEDEBEDCD,CEAEEBDBEACBDDDEBCAEDBACDECDABDCECAACEEADAECA,99999EEACBDEEAECBDBADEEADBEDCADDDDDCDACCCBEDAB...,BDEBCECEBECCDBACAEEBAAAEBBBDECDABBACCECDBCBCB,1,DABCEDEBEEBBCABEDDCBCBECDADCDAACBDCCCDBBBEBAB,EBAAEADBCACBBABEECBAAEEBBBADCBADBCEDDEBBCAEAB,ACABBACAEADCEADABDACDCEABDDADBEDDDEBBACCDDDCCE...,DCCAEBABDDCABEECCBCCEXADDCEECDEBADCABBDBDEDCE,1.0,80.0,160.0,120.0,100.0,140.0,600.0,H,B,A,A,2.0,B,A,B,D,A,A,B,A,A,A,B,A,A,B,A,A,C,A,A,B
2685010,210052405677,2021,4,M,1,1,1,2,0,2,1.0,0,2615409.0,Toritama,26.0,PE,2.0,1.0,1.0,2612505,Santa Cruz do Capibaribe,26,PE,1,1,1,1,910.0,879.0,889.0,900.0,466.3,401.7,384.3,459.4,DDEAEDAEBEDECCACDACAAAAEBADEDEEAEEBADDBCEBDBE,DEBCDACDCDBEAEACACDDCCECBCCBAEACDAEABBEEBBEDB,EDBBE99999AAABAAACECAEBDCDDCBEDEAABADAABCCBDDB...,AABCCADBADCBECAACDABCECCACDAEBBACBBEBADECDCEA,0,ADCDCDBBBECDCCDCBCBDABCAADCBEBABEEBBBCABEDEDE,BADCBADBCEDDEBBADBCABEECCAEABEBAAECBBABAAEEBB,CAABBCAEAABDCDEADCEDBEDDDABBBBDEBCEADABDBACACD...,DDCABDCCAEDCEBBDBDAEEBADCAECDBCCCCDDCEEBABXEE,1.0,80.0,120.0,100.0,100.0,80.0,480.0,E,B,D,C,4.0,B,A,B,B,A,A,B,A,A,A,A,A,A,A,A,A,B,A,A,B
2685013,210054261022,2021,9,M,1,1,1,1,7,1,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2605707,Floresta,26,PE,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,E,E,D,C,2.0,C,A,B,C,A,A,B,A,B,A,B,A,A,C,A,A,B,A,B,B
2685017,210052254346,2021,4,M,1,3,1,2,0,2,1.0,0,2615409.0,Toritama,26.0,PE,2.0,1.0,1.0,2612505,Santa Cruz do Capibaribe,26,PE,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,E,D,D,A,5.0,B,A,B,B,B,A,B,A,A,A,A,A,A,B,A,A,B,A,A,B

## Limpeza e Tratamento da base dos dados

> Processo de preparação, organização e estruturação dos dados.

### Excluindo colunas

> Exclusão de colunas julgadas desnecessárias para as análises futuras.

In [5]:
df_pe2021 = df_pe2021.drop(columns=['NU_ANO', 'TP_ESTADO_CIVIL', 'TP_NACIONALIDADE', 'TP_ENSINO', 'CO_MUNICIPIO_ESC',
                                  'CO_UF_ESC', 'SG_UF_ESC', 'TP_DEPENDENCIA_ADM_ESC', 'TP_SIT_FUNC_ESC', 'CO_MUNICIPIO_PROVA',
                                  'CO_UF_PROVA', 'SG_UF_PROVA', 'CO_PROVA_CN', 'CO_PROVA_CH', 'CO_PROVA_LC', 'CO_PROVA_MT',
                                  'TX_GABARITO_CN', 'TX_GABARITO_CH', 'TX_GABARITO_LC', 'TX_GABARITO_MT',
                                    'TX_RESPOSTAS_CN', 'TX_RESPOSTAS_CH', 'TX_RESPOSTAS_LC', 'TX_RESPOSTAS_MT', 'Q001',
                                  'Q002', 'Q003', 'Q004', 'Q005','Q007', 'Q008', 'Q009', 'Q010', 'Q011', 'Q012',
                                  'Q013', 'Q014', 'Q015', 'Q016', 'Q017', 'Q018', 'Q019', 'Q020', 'Q021', 'Q022', 'Q023', 'Q024',
                                   'TP_ANO_CONCLUIU'])

### Renomeando os registros das linhas

> Padronização e categorização dos dados

In [6]:
df_pe2021['TP_FAIXA_ETARIA'] = df_pe2021['TP_FAIXA_ETARIA'].replace({1: 'Menor de 17 anos',
                                                                    2: '17 anos',
                                                                    3: '18 anos',
                                                                    4: '19 anos',
                                                                    5: '20 anos',
                                                                    6: '21 anos',
                                                                    7: '22 anos',
                                                                    8: '23 anos',
                                                                    9: '24 anos',
                                                                    10: '25 anos',
                                                                    11: 'Entre 26 e 30 anos',
                                                                    12: 'Entre 31 e 35 anos',
                                                                    13: 'Entre 36 e 40 anos',
                                                                    14: 'Entre 41 e 45 anos',
                                                                    15: 'Entre 46 e 50 anos',
                                                                    16: 'Entre 51 e 55 anos',
                                                                    17: 'Entre 56 e 60 anos',
                                                                    18: 'Entre 61 e 65 anos',
                                                                    19: 'Entre 66 e 70 anos',
                                                                    20: 'Maior que 70 anos'})

In [7]:
df_pe2021['TP_COR_RACA'] = df_pe2021['TP_COR_RACA'].replace({0: 'Não declarado',
                                                            1: 'Branca',
                                                            2: 'Preta',
                                                            3: 'Parda',
                                                            4: 'Amarela',
                                                            5: 'Indígena'})

In [8]:
df_pe2021['TP_ST_CONCLUSAO'] = df_pe2021['TP_ST_CONCLUSAO'].replace({1: 'Já concluí o EM',
                                                                    2: 'Estou cursando e concluirei o EM em 2021',
                                                                    3: 'Estou cursando e concluirei o EM após 2021',
                                                                    4: 'Não concluí e não estou cursando o EM'})

In [9]:
df_pe2021['TP_ESCOLA'] = df_pe2021['TP_ESCOLA'].replace({1: 'Não respondeu',
                                                        2: 'Público',
                                                        3: 'Privada',
                                                        4: 'Exterior'})

In [10]:
df_pe2021['IN_TREINEIRO'] = df_pe2021['IN_TREINEIRO'].replace({1: 'Sim',
                                                              0: 'Não'})

In [11]:
df_pe2021['TP_LOCALIZACAO_ESC'] = df_pe2021['TP_LOCALIZACAO_ESC'].replace({1: 'Urbana',
                                                                          2: 'Rural'})

In [12]:
df_pe2021['TP_LINGUA'] = df_pe2021['TP_LINGUA'].replace({0: 'Inglês',
                                                         1: 'Espanhol'})

In [13]:
df_pe2021['TP_STATUS_REDACAO'] = df_pe2021['TP_STATUS_REDACAO'].replace({1: 'Sem problemas',
                                                                        2: 'Anulada',
                                                                        3: 'Cópia Texto Motivador',
                                                                        4: 'Em Branco',
                                                                        6: 'Fuga ao tema',
                                                                        7: 'Não atendimento ao tipo textual',
                                                                        8: 'Texto insuficiente',
                                                                        9: 'Parte desconectada'})

In [14]:
df_pe2021['Q006'] = df_pe2021['Q006'].replace({'A': 'Nenhuma renda',
                                              'B':'Até R$ 998,00',
                                              'C': 'De R$ 998,01 até R$ 1.497,00',
                                              'D': 'De R$ 1.497,01 até R$ 1.996,00',
                                              'E': 'De R$ 1.996,01 até R$ 2.495,00',
                                              'F': 'De R$ 2.495,01 até R$ 2.994,00',
                                              'G': 'De R$ 2.994,01 até R$ 3.992,00',
                                              'H': 'De R$ 3.992,01 até R$ 4.990,00',
                                              'I': 'De R$ 4.990,01 até R$ 5.988,00',
                                              'J': 'De R$ 5.988,01 até R$ 6.986,00',
                                              'K': 'De R$ 6.986,01 até R$ 7.984,00',
                                              'L': 'De R$ 7.984,01 até R$ 8.982,00',
                                              'M': 'De R$ 8.982,01 até R$ 9.980,00',
                                              'N': 'De R$ 9.980,01 até R$ 11.976,00',
                                              'O': 'De R$ 11.976,01 até R$ 14.970,00',
                                              'P': 'De R$ 14.970,01 até R$ 19.960,00',
                                              'Q': 'Mais de R$ 19.960,00'})

In [15]:
df_pe2021['Q025'] = df_pe2021['Q025'].replace({'A': 'Não', 'B': 'Sim'})

### Renomeando as colunas da base de dados

In [16]:
df_pe2021 = df_pe2021.rename(columns={'TP_FAIXA_ETARIA': 'FAIXA ETÁRIA',
                                     'TP_SEXO': 'SEXO',
                                     'TP_COR_RACA': 'COR/RAÇA',
                                     'TP_ST_CONCLUSAO': 'SITUAÇÃO DE CONCLUSÃO',
                                     'TP_ESCOLA': 'TIPO DE ESCOLA',
                                     'TP_LOCALIZACAO_ESC': 'LOCALIZAÇÃO DA ESCOLA',
                                     'TP_LINGUA': 'IDIOMA',
                                     'TP_STATUS_REDACAO': 'STATUS DA REDAÇÃO',
                                     'Q006': 'RENDA',
                                     'Q025': 'INTERNET',
                                     'NU_NOTA_CN': 'NOTA_CN', 'NU_NOTA_CH':'NOTA_CH', 'NU_NOTA_LC':'NOTA_LC', 'NU_NOTA_MT':'NOTA_MT',
                                     'NU_NOTA_COMP1':'NOTA_COMP1', 'NU_NOTA_COMP2':'NOTA_COMP2','NU_NOTA_COMP3':'NOTA_COMP3',
                                      'NU_NOTA_COMP4':'NOTA_COMP4', 'NU_NOTA_COMP5':'NOTA_COMP5', 'NU_NOTA_REDACAO':'NOTA_REDACAO'})

In [17]:
df_pe2021.head()

,NU_INSCRICAO,FAIXA ETÁRIA,SEXO,COR/RAÇA,SITUAÇÃO DE CONCLUSÃO,TIPO DE ESCOLA,IN_TREINEIRO,NO_MUNICIPIO_ESC,LOCALIZAÇÃO DA ESCOLA,NO_MUNICIPIO_PROVA,TP_PRESENCA_CN,TP_PRESENCA_CH,TP_PRESENCA_LC,TP_PRESENCA_MT,NOTA_CN,NOTA_CH,NOTA_LC,NOTA_MT,IDIOMA,STATUS DA REDAÇÃO,NOTA_COMP1,NOTA_COMP2,NOTA_COMP3,NOTA_COMP4,NOTA_COMP5,NOTA_REDACAO,RENDA,INTERNET
16,210053788150,22 anos,F,Branca,Já concluí o EM,Não respondeu,Não,NaN,NaN,São Lourenço da Mata,1,1,1,1,487.9,419.9,488.2,553.1,Inglês,Sem problemas,140.0,120.0,140.0,160.0,160.0,720.0,"Até R$ 998,00",Sim
19,210053797083,Entre 26 e 30 anos,M,Parda,Já concluí o EM,Não respondeu,Não,NaN,NaN,São Lourenço da Mata,1,1,1,1,388.1,602.0,337.1,629.5,Espanhol,Sem problemas,140.0,200.0,140.0,180.0,200.0,860.0,"De R$ 998,01 até R$ 1.497,00",Sim
50,210051819810,19 anos,F,Parda,Já concluí o EM,Não respondeu,Não,NaN,NaN,Timbaúba,1,1,1,1,387.0,486.4,436.9,404.0,Espanhol,Sem problemas,100.0,180.0,120.0,120.0,140.0,660.0,"Até R$ 998,00",Sim
57,210054293853,18 anos,F,Parda,Já concluí o EM,Não respondeu,Não,NaN,NaN,Lagoa Grande,1,1,1,1,507.1,472.2,474.2,506.3,Espanhol,Sem problemas,120.0,120.0,120.0,120.0,100.0,580.0,Nenhuma renda,Sim
69,210054019198,Entre 41 e 45 anos,M,Parda,Já concluí o EM,Não respondeu,Não,NaN,NaN,Recife,0,0,0,0,NaN,NaN,NaN,NaN,Inglês,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"De R$ 1.497,01 até R$ 1.996,00",Sim

### Separar entre vestibulandos e treineiros

> Filtrar apenas para os inscritos considerados vestibulandos e que não estão com o intuito de apenas treinar seus conhecimentos.

In [18]:
vestibulandos = df_pe2021.loc[df_pe2021.IN_TREINEIRO == 'Não']

In [19]:
vestibulandos = vestibulandos.drop(columns=['IN_TREINEIRO','NO_MUNICIPIO_ESC'])

In [20]:
vestibulandos.head()

,NU_INSCRICAO,FAIXA ETÁRIA,SEXO,COR/RAÇA,SITUAÇÃO DE CONCLUSÃO,TIPO DE ESCOLA,LOCALIZAÇÃO DA ESCOLA,NO_MUNICIPIO_PROVA,TP_PRESENCA_CN,TP_PRESENCA_CH,TP_PRESENCA_LC,TP_PRESENCA_MT,NOTA_CN,NOTA_CH,NOTA_LC,NOTA_MT,IDIOMA,STATUS DA REDAÇÃO,NOTA_COMP1,NOTA_COMP2,NOTA_COMP3,NOTA_COMP4,NOTA_COMP5,NOTA_REDACAO,RENDA,INTERNET
16,210053788150,22 anos,F,Branca,Já concluí o EM,Não respondeu,NaN,São Lourenço da Mata,1,1,1,1,487.9,419.9,488.2,553.1,Inglês,Sem problemas,140.0,120.0,140.0,160.0,160.0,720.0,"Até R$ 998,00",Sim
19,210053797083,Entre 26 e 30 anos,M,Parda,Já concluí o EM,Não respondeu,NaN,São Lourenço da Mata,1,1,1,1,388.1,602.0,337.1,629.5,Espanhol,Sem problemas,140.0,200.0,140.0,180.0,200.0,860.0,"De R$ 998,01 até R$ 1.497,00",Sim
50,210051819810,19 anos,F,Parda,Já concluí o EM,Não respondeu,NaN,Timbaúba,1,1,1,1,387.0,486.4,436.9,404.0,Espanhol,Sem problemas,100.0,180.0,120.0,120.0,140.0,660.0,"Até R$ 998,00",Sim
57,210054293853,18 anos,F,Parda,Já concluí o EM,Não respondeu,NaN,Lagoa Grande,1,1,1,1,507.1,472.2,474.2,506.3,Espanhol,Sem problemas,120.0,120.0,120.0,120.0,100.0,580.0,Nenhuma renda,Sim
69,210054019198,Entre 41 e 45 anos,M,Parda,Já concluí o EM,Não respondeu,NaN,Recife,0,0,0,0,NaN,NaN,NaN,NaN,Inglês,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"De R$ 1.497,01 até R$ 1.996,00",Sim

In [21]:
presenca = ['TP_PRESENCA_CN', 'TP_PRESENCA_CH', 'TP_PRESENCA_LC', 'TP_PRESENCA_MT']

In [22]:
vestibulandos['PRESENCA'] = vestibulandos[presenca].sum(axis=1)
vestibulandos.head()

,NU_INSCRICAO,FAIXA ETÁRIA,SEXO,COR/RAÇA,SITUAÇÃO DE CONCLUSÃO,TIPO DE ESCOLA,LOCALIZAÇÃO DA ESCOLA,NO_MUNICIPIO_PROVA,TP_PRESENCA_CN,TP_PRESENCA_CH,TP_PRESENCA_LC,TP_PRESENCA_MT,NOTA_CN,NOTA_CH,NOTA_LC,NOTA_MT,IDIOMA,STATUS DA REDAÇÃO,NOTA_COMP1,NOTA_COMP2,NOTA_COMP3,NOTA_COMP4,NOTA_COMP5,NOTA_REDACAO,RENDA,INTERNET,PRESENCA
16,210053788150,22 anos,F,Branca,Já concluí o EM,Não respondeu,NaN,São Lourenço da Mata,1,1,1,1,487.9,419.9,488.2,553.1,Inglês,Sem problemas,140.0,120.0,140.0,160.0,160.0,720.0,"Até R$ 998,00",Sim,4
19,210053797083,Entre 26 e 30 anos,M,Parda,Já concluí o EM,Não respondeu,NaN,São Lourenço da Mata,1,1,1,1,388.1,602.0,337.1,629.5,Espanhol,Sem problemas,140.0,200.0,140.0,180.0,200.0,860.0,"De R$ 998,01 até R$ 1.497,00",Sim,4
50,210051819810,19 anos,F,Parda,Já concluí o EM,Não respondeu,NaN,Timbaúba,1,1,1,1,387.0,486.4,436.9,404.0,Espanhol,Sem problemas,100.0,180.0,120.0,120.0,140.0,660.0,"Até R$ 998,00",Sim,4
57,210054293853,18 anos,F,Parda,Já concluí o EM,Não respondeu,NaN,Lagoa Grande,1,1,1,1,507.1,472.2,474.2,506.3,Espanhol,Sem problemas,120.0,120.0,120.0,120.0,100.0,580.0,Nenhuma renda,Sim,4
69,210054019198,Entre 41 e 45 anos,M,Parda,Já concluí o EM,Não respondeu,NaN,Recife,0,0,0,0,NaN,NaN,NaN,NaN,Inglês,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"De R$ 1.497,01 até R$ 1.996,00",Sim,0

In [23]:
vestibulandos_presentes = vestibulandos.loc[vestibulandos.PRESENCA != 0]
vestibulandos_presentes.head()

,NU_INSCRICAO,FAIXA ETÁRIA,SEXO,COR/RAÇA,SITUAÇÃO DE CONCLUSÃO,TIPO DE ESCOLA,LOCALIZAÇÃO DA ESCOLA,NO_MUNICIPIO_PROVA,TP_PRESENCA_CN,TP_PRESENCA_CH,TP_PRESENCA_LC,TP_PRESENCA_MT,NOTA_CN,NOTA_CH,NOTA_LC,NOTA_MT,IDIOMA,STATUS DA REDAÇÃO,NOTA_COMP1,NOTA_COMP2,NOTA_COMP3,NOTA_COMP4,NOTA_COMP5,NOTA_REDACAO,RENDA,INTERNET,PRESENCA
16,210053788150,22 anos,F,Branca,Já concluí o EM,Não respondeu,NaN,São Lourenço da Mata,1,1,1,1,487.9,419.9,488.2,553.1,Inglês,Sem problemas,140.0,120.0,140.0,160.0,160.0,720.0,"Até R$ 998,00",Sim,4
19,210053797083,Entre 26 e 30 anos,M,Parda,Já concluí o EM,Não respondeu,NaN,São Lourenço da Mata,1,1,1,1,388.1,602.0,337.1,629.5,Espanhol,Sem problemas,140.0,200.0,140.0,180.0,200.0,860.0,"De R$ 998,01 até R$ 1.497,00",Sim,4
50,210051819810,19 anos,F,Parda,Já concluí o EM,Não respondeu,NaN,Timbaúba,1,1,1,1,387.0,486.4,436.9,404.0,Espanhol,Sem problemas,100.0,180.0,120.0,120.0,140.0,660.0,"Até R$ 998,00",Sim,4
57,210054293853,18 anos,F,Parda,Já concluí o EM,Não respondeu,NaN,Lagoa Grande,1,1,1,1,507.1,472.2,474.2,506.3,Espanhol,Sem problemas,120.0,120.0,120.0,120.0,100.0,580.0,Nenhuma renda,Sim,4
76,210051930402,17 anos,F,Branca,Estou cursando e concluirei o EM em 2021,Privada,Urbana,Surubim,1,1,1,1,587.8,591.6,558.9,644.1,Espanhol,Sem problemas,140.0,180.0,120.0,180.0,200.0,820.0,"De R$ 1.497,01 até R$ 1.996,00",Sim,4

In [24]:
notas = ['NOTA_CN', 'NOTA_CH', 'NOTA_LC', 'NOTA_MT', 'NOTA_REDACAO']
vestibulandos_presentes['NOTAS'] = vestibulandos_presentes[notas].sum(axis=1)
vestibulandos_presentes.head()

C:\Users\victo\AppData\Local\Temp\ipykernel_50516\3346175007.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  vestibulandos_presentes['NOTAS'] = vestibulandos_presentes[notas].sum(axis=1)

,NU_INSCRICAO,FAIXA ETÁRIA,SEXO,COR/RAÇA,SITUAÇÃO DE CONCLUSÃO,TIPO DE ESCOLA,LOCALIZAÇÃO DA ESCOLA,NO_MUNICIPIO_PROVA,TP_PRESENCA_CN,TP_PRESENCA_CH,TP_PRESENCA_LC,TP_PRESENCA_MT,NOTA_CN,NOTA_CH,NOTA_LC,NOTA_MT,IDIOMA,STATUS DA REDAÇÃO,NOTA_COMP1,NOTA_COMP2,NOTA_COMP3,NOTA_COMP4,NOTA_COMP5,NOTA_REDACAO,RENDA,INTERNET,PRESENCA,NOTAS
16,210053788150,22 anos,F,Branca,Já concluí o EM,Não respondeu,NaN,São Lourenço da Mata,1,1,1,1,487.9,419.9,488.2,553.1,Inglês,Sem problemas,140.0,120.0,140.0,160.0,160.0,720.0,"Até R$ 998,00",Sim,4,2669.1
19,210053797083,Entre 26 e 30 anos,M,Parda,Já concluí o EM,Não respondeu,NaN,São Lourenço da Mata,1,1,1,1,388.1,602.0,337.1,629.5,Espanhol,Sem problemas,140.0,200.0,140.0,180.0,200.0,860.0,"De R$ 998,01 até R$ 1.497,00",Sim,4,2816.7
50,210051819810,19 anos,F,Parda,Já concluí o EM,Não respondeu,NaN,Timbaúba,1,1,1,1,387.0,486.4,436.9,404.0,Espanhol,Sem problemas,100.0,180.0,120.0,120.0,140.0,660.0,"Até R$ 998,00",Sim,4,2374.3
57,210054293853,18 anos,F,Parda,Já concluí o EM,Não respondeu,NaN,Lagoa Grande,1,1,1,1,507.1,472.2,474.2,506.3,Espanhol,Sem problemas,120.0,120.0,120.0,120.0,100.0,580.0,Nenhuma renda,Sim,4,2539.8
76,210051930402,17 anos,F,Branca,Estou cursando e concluirei o EM em 2021,Privada,Urbana,Surubim,1,1,1,1,587.8,591.6,558.9,644.1,Espanhol,Sem problemas,140.0,180.0,120.0,180.0,200.0,820.0,"De R$ 1.497,01 até R$ 1.996,00",Sim,4,3202.4

In [25]:
df_remove = vestibulandos_presentes.loc[vestibulandos_presentes['NOTAS'] == 0]

In [26]:
df_remove.head()

,NU_INSCRICAO,FAIXA ETÁRIA,SEXO,COR/RAÇA,SITUAÇÃO DE CONCLUSÃO,TIPO DE ESCOLA,LOCALIZAÇÃO DA ESCOLA,NO_MUNICIPIO_PROVA,TP_PRESENCA_CN,TP_PRESENCA_CH,TP_PRESENCA_LC,TP_PRESENCA_MT,NOTA_CN,NOTA_CH,NOTA_LC,NOTA_MT,IDIOMA,STATUS DA REDAÇÃO,NOTA_COMP1,NOTA_COMP2,NOTA_COMP3,NOTA_COMP4,NOTA_COMP5,NOTA_REDACAO,RENDA,INTERNET,PRESENCA,NOTAS
22255,210052817497,23 anos,F,Branca,Já concluí o EM,Não respondeu,NaN,Escada,0,1,1,0,NaN,0.0,0.0,NaN,Espanhol,Em Branco,0.0,0.0,0.0,0.0,0.0,0.0,"De R$ 1.996,01 até R$ 2.495,00",Sim,2,0.0
28229,210053819873,17 anos,F,Parda,Estou cursando e concluirei o EM em 2021,Público,NaN,Paulista,0,2,2,0,NaN,NaN,NaN,NaN,Inglês,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"De R$ 1.497,01 até R$ 1.996,00",Sim,4,0.0
38487,210052051368,19 anos,M,Não declarado,Já concluí o EM,Não respondeu,NaN,Olinda,0,1,1,0,NaN,0.0,0.0,NaN,Inglês,Em Branco,0.0,0.0,0.0,0.0,0.0,0.0,"De R$ 2.495,01 até R$ 2.994,00",Sim,2,0.0
38752,210052917893,Entre 41 e 45 anos,M,Parda,Já concluí o EM,Não respondeu,NaN,Escada,0,2,2,0,NaN,NaN,NaN,NaN,Espanhol,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"De R$ 2.994,01 até R$ 3.992,00",Sim,4,0.0
45733,210051617898,Entre 31 e 35 anos,F,Branca,Já concluí o EM,Não respondeu,NaN,Garanhuns,0,2,2,0,NaN,NaN,NaN,NaN,Inglês,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"Até R$ 998,00",Sim,4,0.0

In [27]:
vestibulandos_presentes_pe = vestibulandos_presentes.drop(df_remove.index)

In [28]:
vestibulandos_presentes_pe

,NU_INSCRICAO,FAIXA ETÁRIA,SEXO,COR/RAÇA,SITUAÇÃO DE CONCLUSÃO,TIPO DE ESCOLA,LOCALIZAÇÃO DA ESCOLA,NO_MUNICIPIO_PROVA,TP_PRESENCA_CN,TP_PRESENCA_CH,TP_PRESENCA_LC,TP_PRESENCA_MT,NOTA_CN,NOTA_CH,NOTA_LC,NOTA_MT,IDIOMA,STATUS DA REDAÇÃO,NOTA_COMP1,NOTA_COMP2,NOTA_COMP3,NOTA_COMP4,NOTA_COMP5,NOTA_REDACAO,RENDA,INTERNET,PRESENCA,NOTAS
16,210053788150,22 anos,F,Branca,Já concluí o EM,Não respondeu,NaN,São Lourenço da Mata,1,1,1,1,487.9,419.9,488.2,553.1,Inglês,Sem problemas,140.0,120.0,140.0,160.0,160.0,720.0,"Até R$ 998,00",Sim,4,2669.1
19,210053797083,Entre 26 e 30 anos,M,Parda,Já concluí o EM,Não respondeu,NaN,São Lourenço da Mata,1,1,1,1,388.1,602.0,337.1,629.5,Espanhol,Sem problemas,140.0,200.0,140.0,180.0,200.0,860.0,"De R$ 998,01 até R$ 1.497,00",Sim,4,2816.7
50,210051819810,19 anos,F,Parda,Já concluí o EM,Não respondeu,NaN,Timbaúba,1,1,1,1,387.0,486.4,436.9,404.0,Espanhol,Sem problemas,100.0,180.0,120.0,120.0,140.0,660.0,"Até R$ 998,00",Sim,4,2374.3
57,210054293853,18 anos,F,Parda,Já concluí o EM,Não respondeu,NaN,Lagoa Grande,1,1,1,1,507.1,472.2,474.2,506.3,Espanhol,Sem problemas,120.0,120.0,120.0,120.0,100.0,580.0,Nenhuma renda,Sim,4,2539.8
76,210051930402,17 anos,F,Branca,Estou cursando e concluirei o EM em 2021,Privada,Urbana,Surubim,1,1,1,1,587.8,591.6,558.9,644.1,Espanhol,Sem problemas,140.0,180.0,120.0,180.0,200.0,820.0,"De R$ 1.497,01 até R$ 1.996,00",Sim,4,3202.4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2684875,210051099084,Entre 31 e 35 anos,F,Parda,Já concluí o EM,Não respondeu,NaN,Olinda,0,1,1,0,NaN,439.3,377.8,NaN,Espanhol,Fuga ao tema,0.0,0.0,0.0,0.0,0.0,0.0,"Até R$ 998,00",Sim,2,817.1
2684881,210052900056,25 anos,F,Branca,Já concluí o EM,Não respondeu,NaN,Recife,1,1,1,1,654.9,727.2,610.9,662.3,Inglês,Sem problemas,160.0,160.0,140.0,180.0,200.0,840.0,"De R$ 2.994,01 até R$ 3.992,00",Sim,4,3495.3
2684951,210051146292,17 anos,F,Branca,Já concluí o EM,Não respondeu,NaN,Jaboatão dos Guararapes,1,1,1,1,553.6,553.8,557.7,593.5,Inglês,Sem problemas,120.0,120.0,80.0,120.0,100.0,540.0,"De R$ 4.990,01 até R$ 5.988,00",Sim,4,2798.6
2684977,210053824236,21 anos,F,Branca,Já concluí o EM,Não respondeu,NaN,Surubim,1,1,1,1,440.2,463.7,487.6,391.1,Espanhol,Sem problemas,80.0,160.0,120.0,100.0,140.0,600.0,"Até R$ 998,00",Sim,4,2382.6
2685010,210052405677,19 anos,M,Branca,Estou cursando e concluirei o EM em 2021,Público,Urbana,Santa Cruz do Capibaribe,1,1,1,1,466.3,401.7,384.3,459.4,Inglês,Sem problemas,80.0,120.0,100.0,100.0,80.0,480.0,"Até R$ 998,00",Sim,4,2191.7

#### Neste momento, temos a base de dados dentro dos parâmetros escolhidos para as análises futuras.

In [29]:
# Confirmacao de que todas as linhas com as 5 notas zeradas estão fora da base de dados
vestibulandos_presentes_pe.loc[vestibulandos_presentes_pe['NOTAS'] == 0]

Empty DataFrame
Columns: [NU_INSCRICAO, FAIXA ETÁRIA, SEXO, COR/RAÇA, SITUAÇÃO DE CONCLUSÃO, TIPO DE ESCOLA, LOCALIZAÇÃO DA ESCOLA, NO_MUNICIPIO_PROVA, TP_PRESENCA_CN, TP_PRESENCA_CH, TP_PRESENCA_LC, TP_PRESENCA_MT, NOTA_CN, NOTA_CH, NOTA_LC, NOTA_MT, IDIOMA, STATUS DA REDAÇÃO, NOTA_COMP1, NOTA_COMP2, NOTA_COMP3, NOTA_COMP4, NOTA_COMP5, NOTA_REDACAO, RENDA, INTERNET, PRESENCA, NOTAS]
Index: []

### Substituição dos valores ausentes de acordo com o tipo da variável

In [30]:
vestibulandos_presentes_pe['LOCALIZAÇÃO DA ESCOLA'] = vestibulandos_presentes_pe['LOCALIZAÇÃO DA ESCOLA'].fillna('Não Consta')

In [31]:
vestibulandos_presentes_pe['NOTA_CN'] = vestibulandos_presentes_pe['NOTA_CN'].fillna(0)
vestibulandos_presentes_pe['NOTA_CH'] = vestibulandos_presentes_pe['NOTA_CH'].fillna(0)
vestibulandos_presentes_pe['NOTA_LC'] = vestibulandos_presentes_pe['NOTA_LC'].fillna(0)
vestibulandos_presentes_pe['NOTA_MT'] = vestibulandos_presentes_pe['NOTA_MT'].fillna(0)

vestibulandos_presentes_pe['NOTA_COMP1'] = vestibulandos_presentes_pe['NOTA_COMP1'].fillna(0)
vestibulandos_presentes_pe['NOTA_COMP2'] = vestibulandos_presentes_pe['NOTA_COMP2'].fillna(0)
vestibulandos_presentes_pe['NOTA_COMP3'] = vestibulandos_presentes_pe['NOTA_COMP3'].fillna(0)
vestibulandos_presentes_pe['NOTA_COMP4'] = vestibulandos_presentes_pe['NOTA_COMP4'].fillna(0)
vestibulandos_presentes_pe['NOTA_COMP5'] = vestibulandos_presentes_pe['NOTA_COMP5'].fillna(0)
vestibulandos_presentes_pe['NOTA_REDACAO'] = vestibulandos_presentes_pe['NOTA_REDACAO'].fillna(0)

In [32]:
vestibulandos_presentes_pe['STATUS DA REDAÇÃO'] = vestibulandos_presentes_pe['STATUS DA REDAÇÃO'].fillna('Não Consta')

In [33]:
vestibulandos_presentes_pe.head()

,NU_INSCRICAO,FAIXA ETÁRIA,SEXO,COR/RAÇA,SITUAÇÃO DE CONCLUSÃO,TIPO DE ESCOLA,LOCALIZAÇÃO DA ESCOLA,NO_MUNICIPIO_PROVA,TP_PRESENCA_CN,TP_PRESENCA_CH,TP_PRESENCA_LC,TP_PRESENCA_MT,NOTA_CN,NOTA_CH,NOTA_LC,NOTA_MT,IDIOMA,STATUS DA REDAÇÃO,NOTA_COMP1,NOTA_COMP2,NOTA_COMP3,NOTA_COMP4,NOTA_COMP5,NOTA_REDACAO,RENDA,INTERNET,PRESENCA,NOTAS
16,210053788150,22 anos,F,Branca,Já concluí o EM,Não respondeu,Não Consta,São Lourenço da Mata,1,1,1,1,487.9,419.9,488.2,553.1,Inglês,Sem problemas,140.0,120.0,140.0,160.0,160.0,720.0,"Até R$ 998,00",Sim,4,2669.1
19,210053797083,Entre 26 e 30 anos,M,Parda,Já concluí o EM,Não respondeu,Não Consta,São Lourenço da Mata,1,1,1,1,388.1,602.0,337.1,629.5,Espanhol,Sem problemas,140.0,200.0,140.0,180.0,200.0,860.0,"De R$ 998,01 até R$ 1.497,00",Sim,4,2816.7
50,210051819810,19 anos,F,Parda,Já concluí o EM,Não respondeu,Não Consta,Timbaúba,1,1,1,1,387.0,486.4,436.9,404.0,Espanhol,Sem problemas,100.0,180.0,120.0,120.0,140.0,660.0,"Até R$ 998,00",Sim,4,2374.3
57,210054293853,18 anos,F,Parda,Já concluí o EM,Não respondeu,Não Consta,Lagoa Grande,1,1,1,1,507.1,472.2,474.2,506.3,Espanhol,Sem problemas,120.0,120.0,120.0,120.0,100.0,580.0,Nenhuma renda,Sim,4,2539.8
76,210051930402,17 anos,F,Branca,Estou cursando e concluirei o EM em 2021,Privada,Urbana,Surubim,1,1,1,1,587.8,591.6,558.9,644.1,Espanhol,Sem problemas,140.0,180.0,120.0,180.0,200.0,820.0,"De R$ 1.497,01 até R$ 1.996,00",Sim,4,3202.4

In [34]:
vestibulandos_presentes_pe.to_csv('enem2021_processed.csv', sep=';', encoding='iso-8859-1')