# Análise de Dados das Notas dos Enem de Pernambuco

### Disciplina: Tópicos Avançados em Gerencimento de Dados e Informações
### Alunos: Maria Teresa e Victor Amarante

## Importar bibliotecas

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import plotly.express as px
from scipy import stats

pd.set_option('display.max_columns', None)

## Importar base de dados

In [2]:
df2019 = pd.read_csv('enem2019.csv', sep=';', encoding='iso-8859-1')

## Visualização da base de dados

In [3]:
df2019

,NU_INSCRICAO,NU_ANO,TP_FAIXA_ETARIA,TP_SEXO,TP_ESTADO_CIVIL,TP_COR_RACA,TP_NACIONALIDADE,TP_ST_CONCLUSAO,TP_ANO_CONCLUIU,TP_ESCOLA,TP_ENSINO,IN_TREINEIRO,CO_MUNICIPIO_ESC,NO_MUNICIPIO_ESC,CO_UF_ESC,SG_UF_ESC,TP_DEPENDENCIA_ADM_ESC,TP_LOCALIZACAO_ESC,TP_SIT_FUNC_ESC,CO_MUNICIPIO_PROVA,NO_MUNICIPIO_PROVA,CO_UF_PROVA,SG_UF_PROVA,TP_PRESENCA_CN,TP_PRESENCA_CH,TP_PRESENCA_LC,TP_PRESENCA_MT,CO_PROVA_CN,CO_PROVA_CH,CO_PROVA_LC,CO_PROVA_MT,NU_NOTA_CN,NU_NOTA_CH,NU_NOTA_LC,NU_NOTA_MT,TX_RESPOSTAS_CN,TX_RESPOSTAS_CH,TX_RESPOSTAS_LC,TX_RESPOSTAS_MT,TP_LINGUA,TX_GABARITO_CN,TX_GABARITO_CH,TX_GABARITO_LC,TX_GABARITO_MT,TP_STATUS_REDACAO,NU_NOTA_COMP1,NU_NOTA_COMP2,NU_NOTA_COMP3,NU_NOTA_COMP4,NU_NOTA_COMP5,NU_NOTA_REDACAO,Q001,Q002,Q003,Q004,Q005,Q006,Q007,Q008,Q009,Q010,Q011,Q012,Q013,Q014,Q015,Q016,Q017,Q018,Q019,Q020,Q021,Q022,Q023,Q024,Q025
0,190001595656,2019,13,M,1,3,1,1,11,1,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3552205,Sorocaba,35,SP,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,B,B,A,A,2,A,A,B,C,A,A,B,A,A,A,A,A,A,A,A,A,C,A,C,B
1,190001421546,2019,8,M,1,1,1,1,5,1,1.0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2910800,Feira de Santana,29,BA,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,C,E,B,B,4,C,A,B,C,A,A,B,A,A,A,A,A,A,B,A,A,E,A,A,B
2,190001133210,2019,13,F,1,3,1,1,13,1,1.0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2304400,Fortaleza,23,CE,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,E,E,B,C,2,B,A,B,B,A,A,B,A,A,A,A,A,A,B,A,A,C,A,A,B
3,190001199383,2019,10,F,1,1,1,1,4,1,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1721000,Palmas,17,TO,1,1,1,1,504.0,510.0,513.0,516.0,483.8,503.6,537.3,392.0,BACCEEBEECDBEDDAEECDEDEADEBBCDBCAACADEEACCBBD,AECEDADAABAADBAADAEBACBAECCDAEADCDBBECCEDABCD,99999AAABEBBCCBDCAEECADBACAADAECCCDCCBAEBDEEEA...,DDBBBBCDCCDCAECCBBECDAEBADCD..CABCCECAEBDBBDA,1,BEEAAEBEEBADEADDADAEABCEDDDBCBCBCCACBCDADCCEB,EEBCEEDBADBBCBABCCADCEBACDBBACCACACBEADBBADCB,ADBBEDCABAABBCBCDAAECDDDBAAAECADECDCEBDEEAECBD...,BEDEEEAADBEBACABCDBABECECACADCBDCCEDCDABECDDD,1.0,120.0,120.0,120.0,100.0,0.0,460.0,C,E,B,D,4,E,A,C,C,A,B,B,A,B,A,A,A,A,C,A,B,D,A,B,B
4,190001237802,2019,7,F,1,1,1,1,4,1,1.0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3118601,Contagem,31,MG,1,1,1,1,504.0,510.0,513.0,516.0,513.6,575.5,570.7,677.0,EEBEDEEEEEBDCEEBEEEEABEEBEEBAEDEECECCDBCECEAE,EEDCCEDDBCBEABAAABADCEDABDBBCBDCCCCDAEDEDBDCB,ABBBE99999ABBCACCCAEEEDCCDADCCAEDEDDEEDBBDECBD...,CDEEEEEAEECBABABCDCACEEEEEEDEEACEAEDEBEEECEDE,0,BEEAAEBEEBADEADDADAEABCEDDDBCBCBCCACBCDADCCEB,EEBCEEDBADBBCBABCCADCEBACDBBACCACACBEADBBADCB,ADBBEDCABAABBCBCDAAECDDDBAAAECADECDCEBDEEAECBD...,BEDEEEAADBEBACABCDBABECECACADCBDCCEDCDABECDDD,1.0,160.0,120.0,180.0,200.0,200.0,860.0,E,E,C,C,3,G,A,C,D,B,A,B,B,B,A,B,A,A,B,A,A,C,B,B,B
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5095166,190006074437,2019,14,F,4,3,1,1,13,1,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5300108,Brasília,53,DF,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,E,B,C,F,4,C,A,B,C,A,A,B,A,B,B,B,A,A,B,A,A,B,B,A,B
5095167,190005429225,2019,5,M,1,3,1,1,3,1,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1302603,Manaus,13,AM,0,1,1,0,NaN,509.0,514.0,NaN,NaN,578.9,555.5,NaN,NaN,DAABAEACCBAEADBDCAEDBDEBCEBAECEBBDBBEEABCDADC,99999CABEABCCBCDBAEBBAADBECCEEAADBEEDDEACDCBCE...,NaN,1,NaN,ACACEEBCCBABADBBBACDBBACCCCADCEBADCBEEDBBEADB,EBBADCABDABACBCEBDEEAAADDBECDECDDBADBCDAAECBCC...,NaN,1.0,100.0,120.0,100.0,120.0,60.0,500.0,C,F,A,D,7,C,A,B,C,A,A,B,A,B,B,A,A,A,B,B,A,E,A,A,B
5095168,190006087652,2019,6,M,0,0,1,1,3,1,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4302105,Bento Gonçalves,43,RS,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,E,E,D,D,3,C,A,B,C,B,A,B,A,B,A,A,A,A,B,A,A,C,B,B,B
5095169,190006087653,2019,7,M,0,0,1,1,3,1,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4302105,Bento Gonçalves,43,RS,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,H,C,F,F,3,A,A,B,C,A,A,B,B,B,A,B,A,A,C,B,B,A,A,A,B
5095170,190006087654,2019,6,F,0,0,1,1,3,1,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4302105,Bento Gonçalves,43,RS,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,H,H,F,F,3,C,A,B,C,B,A,B,A,B,A,A,A,A,B,A,A,B,B,B,B

## Filtrando a base de dados para o estado de Pernambuco

In [4]:
df_pe2019 = df2019.query('SG_UF_PROVA == "PE"')

## Limpeza e Tratamento da base dos dados

> Processo de preparação, organização e estruturação dos dados.

In [5]:
df_pe2019

,NU_INSCRICAO,NU_ANO,TP_FAIXA_ETARIA,TP_SEXO,TP_ESTADO_CIVIL,TP_COR_RACA,TP_NACIONALIDADE,TP_ST_CONCLUSAO,TP_ANO_CONCLUIU,TP_ESCOLA,TP_ENSINO,IN_TREINEIRO,CO_MUNICIPIO_ESC,NO_MUNICIPIO_ESC,CO_UF_ESC,SG_UF_ESC,TP_DEPENDENCIA_ADM_ESC,TP_LOCALIZACAO_ESC,TP_SIT_FUNC_ESC,CO_MUNICIPIO_PROVA,NO_MUNICIPIO_PROVA,CO_UF_PROVA,SG_UF_PROVA,TP_PRESENCA_CN,TP_PRESENCA_CH,TP_PRESENCA_LC,TP_PRESENCA_MT,CO_PROVA_CN,CO_PROVA_CH,CO_PROVA_LC,CO_PROVA_MT,NU_NOTA_CN,NU_NOTA_CH,NU_NOTA_LC,NU_NOTA_MT,TX_RESPOSTAS_CN,TX_RESPOSTAS_CH,TX_RESPOSTAS_LC,TX_RESPOSTAS_MT,TP_LINGUA,TX_GABARITO_CN,TX_GABARITO_CH,TX_GABARITO_LC,TX_GABARITO_MT,TP_STATUS_REDACAO,NU_NOTA_COMP1,NU_NOTA_COMP2,NU_NOTA_COMP3,NU_NOTA_COMP4,NU_NOTA_COMP5,NU_NOTA_REDACAO,Q001,Q002,Q003,Q004,Q005,Q006,Q007,Q008,Q009,Q010,Q011,Q012,Q013,Q014,Q015,Q016,Q017,Q018,Q019,Q020,Q021,Q022,Q023,Q024,Q025
15,190001493186,2019,4,M,1,2,1,1,1,1,1.0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2611606,Recife,26,PE,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,D,B,C,F,4,B,A,B,C,A,A,B,A,B,A,B,A,A,B,A,A,C,B,A,B
17,190001493187,2019,6,F,1,3,1,1,4,1,1.0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2611606,Recife,26,PE,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,D,C,B,B,3,B,A,B,C,A,A,B,A,B,A,B,A,A,B,A,A,C,A,A,B
43,190001493188,2019,7,M,1,1,1,1,1,1,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2611606,Recife,26,PE,1,1,1,1,506.0,509.0,514.0,517.0,532.2,533.8,558.1,509.8,DEDDEEBEEEBEADACCADBABBABDEBBEDEBDADCABEEBBAB,ACAEACDCABACABBAEAEABBCEACEEBCCABACBAEDAAACBB,EBAAD99999BACBDEBDBBDADDBDAEDECDDADCECBAADCAEB...,AAAABCECEECCCDACACBDBAEABCCBAEAEDDDAABEDBABBB,0,DEADBAAAEBEECEBCBCBCBDADAEABCEDDDDADCBEECACBC,ACACEEBCCBABADBBBACDBBACCCCADCEBADCBEEDBBEADB,EBBADCABDABACBCEBDEEAAADDBECDECDDBADBCDAAECBCC...,AADDDBEEEBEDDBEBACABCDBABECECACAECDCBDCCEDCDA,1.0,100.0,140.0,120.0,120.0,160.0,640.0,C,D,C,B,6,E,A,B,D,A,A,B,A,B,A,B,A,B,B,B,A,A,B,B,B
47,190001493189,2019,15,M,1,1,1,1,13,1,1.0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2611101,Petrolina,26,PE,1,1,1,1,503.0,510.0,513.0,515.0,442.1,450.6,496.8,493.2,DCEBDAECCBDDCDAABDECEBCDBEEDAAACEDDDACBEABABC,BCADCEEEADDCDAADECEDACAAACBDEEADCCBEAEABBADEA,99999EDACBABDCADCAAEDADBCDAADCEEAECECBBBDACEEB...,CDBEACBCABEAABEAACCCACADCCEBDEEDAEBBEDDBAEBBA,1,AAECACDEADCBCDDDBCBDADAEABCEBABEEBCBEECEBDADC,EEBCEEDBADBBCBABCCADCEBACDBBACCACACBEADBBADCB,ADBBEDCABAABBCBCDAAECDDDBAAAECADECDCEBDEEAECBD...,EEEADBEBACABCDBABECECACDCBDCCEDCDABEDECDDDBAA,1.0,120.0,120.0,100.0,120.0,0.0,460.0,A,A,A,A,1,B,A,B,C,A,A,B,A,B,A,B,A,A,B,B,A,B,A,B,A
65,190001493190,2019,12,M,2,3,1,1,11,1,1.0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2611606,Recife,26,PE,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,B,C,B,F,3,B,A,C,C,A,A,B,A,B,A,B,A,A,B,A,A,C,A,A,B
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5094992,190005599641,2019,4,M,1,4,1,1,1,1,1.0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2607901,Jaboatão dos Guararapes,26,PE,1,1,1,1,503.0,508.0,512.0,515.0,434.1,488.4,543.4,474.3,ACEBBCDDDDDDABBCBACDBECDDACEAEABBDBCDADCACACB,DBCBADDACAAABCABBCBAADDAABEBABEADBEBBCCBCDEBB,BBABD99999ACABDECBCCCAABCCADACECEDBCADBEECCECA...,BCBEDBDCBCCBEDECACCEDBBACCAEBBCCBEBCECEDBBDCC,0,AAECACDEADCBCDDDBCBDADAEABCEBABEEBCBEECEBDADC,CBABADBBCEEEBCBADCBEEDBBEADBBACDBBACCCCADACAC,BBEDABDACACBABAECBBCCADCEBDBBCDDEEAAADDBECDECA...,EEEADBEBACABCDBABECECACDCBDCCEDCDABEDECDDDBAA,1.0,120.0,120.0,80.0,120.0,80.0,520.0,E,D,B,B,4,C,A,B,C,A,A,B,A,B,B,B,A,A,C,A,A,D,A,A,B
5095062,190005599642,2019,1,M,0,1,1,3,0,1,NaN,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2611606,Recife,26,PE,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,E,C,D,B,4,E,A,C,E,A,A,C,A,B,B,A,A,B,E,B,A,E,B,B,B
5095083,190005599643,2019,5,F,1,3,1,1,1,1,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2610707,Paulista,26,PE,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,G,F,E,E,5,P,B,E,E,D,A,B,B,B,A,B,A,A,E,B,B,B,B,C,B
5095086,190005599644,2019,4,F,1,1,1,1,2,1,1.0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2602605,Brejo da Madre de Deus,26,PE,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,B,E,C,B,5,C,A,B,C,A,A,B,A,A,A,A,A,A,B,A,A,B,A,A,A
5095145,190005601988,2019,14,M,2,1,1,1,13,1,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2616407,Vitória de Santo Antão,26,PE,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,E,E,D,D,4,E,B,D,D,B,A,B,A,B,A,B,B,B,C,A,B,D,A,B,B

### Excluindo colunas

> Exclusão de colunas julgadas desnecessárias para as análises futuras.

In [6]:
df_pe2019 = df_pe2019.drop(columns=['NU_ANO', 'TP_ESTADO_CIVIL', 'TP_NACIONALIDADE', 'TP_ENSINO', 'CO_MUNICIPIO_ESC',
                                  'CO_UF_ESC', 'SG_UF_ESC', 'TP_DEPENDENCIA_ADM_ESC', 'TP_SIT_FUNC_ESC', 'CO_MUNICIPIO_PROVA',
                                  'CO_UF_PROVA', 'SG_UF_PROVA', 'CO_PROVA_CN', 'CO_PROVA_CH', 'CO_PROVA_LC', 'CO_PROVA_MT',
                                  'TX_GABARITO_CN', 'TX_GABARITO_CH', 'TX_GABARITO_LC', 'TX_GABARITO_MT',
                                    'TX_RESPOSTAS_CN', 'TX_RESPOSTAS_CH', 'TX_RESPOSTAS_LC', 'TX_RESPOSTAS_MT', 'Q001',
                                  'Q002', 'Q003', 'Q004', 'Q005','Q007', 'Q008', 'Q009', 'Q010', 'Q011', 'Q012',
                                  'Q013', 'Q014', 'Q015', 'Q016', 'Q017', 'Q018', 'Q019', 'Q020', 'Q021', 'Q022', 'Q023', 'Q024',
                                   'TP_ANO_CONCLUIU'])

### Renomeando os registros das linhas (categorização)

> Padronização e categorização dos dados

In [7]:
df_pe2019['TP_FAIXA_ETARIA'] = df_pe2019['TP_FAIXA_ETARIA'].replace({1: 'Menor de 17 anos',
                                                                    2: '17 anos',
                                                                    3: '18 anos',
                                                                    4: '19 anos',
                                                                    5: '20 anos',
                                                                    6: '21 anos',
                                                                    7: '22 anos',
                                                                    8: '23 anos',
                                                                    9: '24 anos',
                                                                    10: '25 anos',
                                                                    11: 'Entre 26 e 30 anos',
                                                                    12: 'Entre 31 e 35 anos',
                                                                    13: 'Entre 36 e 40 anos',
                                                                    14: 'Entre 41 e 45 anos',
                                                                    15: 'Entre 46 e 50 anos',
                                                                    16: 'Entre 51 e 55 anos',
                                                                    17: 'Entre 56 e 60 anos',
                                                                    18: 'Entre 61 e 65 anos',
                                                                    19: 'Entre 66 e 70 anos',
                                                                    20: 'Maior que 70 anos'})

In [8]:
df_pe2019['TP_COR_RACA'] = df_pe2019['TP_COR_RACA'].replace({0: 'Não declarado',
                                                            1: 'Branca',
                                                            2: 'Preta',
                                                            3: 'Parda',
                                                            4: 'Amarela',
                                                            5: 'Indígena'})

In [9]:
df_pe2019['TP_ST_CONCLUSAO'] = df_pe2019['TP_ST_CONCLUSAO'].replace({1: 'Já concluí o EM',
                                                                    2: 'Estou cursando e concluirei o EM em 2019',
                                                                    3: 'Estou cursando e concluirei o EM após 2019',
                                                                    4: 'Não concluí e não estou cursando o EM'})

In [10]:
df_pe2019['TP_ESCOLA'] = df_pe2019['TP_ESCOLA'].replace({1: 'Não respondeu',
                                                        2: 'Público',
                                                        3: 'Privada',
                                                        4: 'Exterior'})

In [11]:
df_pe2019['IN_TREINEIRO'] = df_pe2019['IN_TREINEIRO'].replace({1: 'Sim',
                                                              0: 'Não'})

In [12]:
df_pe2019['TP_LOCALIZACAO_ESC'] = df_pe2019['TP_LOCALIZACAO_ESC'].replace({1: 'Urbana',
                                                                          2: 'Rural'})

In [13]:
df_pe2019['TP_LINGUA'] = df_pe2019['TP_LINGUA'].replace({0: 'Inglês',
                                                         1: 'Espanhol'})

In [14]:
df_pe2019['TP_STATUS_REDACAO'] = df_pe2019['TP_STATUS_REDACAO'].replace({1: 'Sem problemas',
                                                                        2: 'Anulada',
                                                                        3: 'Cópia Texto Motivador',
                                                                        4: 'Em Branco',
                                                                        6: 'Fuga ao tema',
                                                                        7: 'Não atendimento ao tipo textual',
                                                                        8: 'Texto insuficiente',
                                                                        9: 'Parte desconectada'})

In [15]:
df_pe2019['Q006'] = df_pe2019['Q006'].replace({'A': 'Nenhuma renda',
                                              'B':'Até R$ 998,00',
                                              'C': 'De R$ 998,01 até R$ 1.497,00',
                                              'D': 'De R$ 1.497,01 até R$ 1.996,00',
                                              'E': 'De R$ 1.996,01 até R$ 2.495,00',
                                              'F': 'De R$ 2.495,01 até R$ 2.994,00',
                                              'G': 'De R$ 2.994,01 até R$ 3.992,00',
                                              'H': 'De R$ 3.992,01 até R$ 4.990,00',
                                              'I': 'De R$ 4.990,01 até R$ 5.988,00',
                                              'J': 'De R$ 5.988,01 até R$ 6.986,00',
                                              'K': 'De R$ 6.986,01 até R$ 7.984,00',
                                              'L': 'De R$ 7.984,01 até R$ 8.982,00',
                                              'M': 'De R$ 8.982,01 até R$ 9.980,00',
                                              'N': 'De R$ 9.980,01 até R$ 11.976,00',
                                              'O': 'De R$ 11.976,01 até R$ 14.970,00',
                                              'P': 'De R$ 14.970,01 até R$ 19.960,00',
                                              'Q': 'Mais de R$ 19.960,00'})

In [16]:
df_pe2019['Q025'] = df_pe2019['Q025'].replace({'A': 'Não', 'B': 'Sim'})

### Renomeando as colunas da base de dados

In [17]:
df_pe2019 = df_pe2019.rename(columns={'TP_FAIXA_ETARIA': 'FAIXA ETÁRIA',
                                     'TP_SEXO': 'SEXO',
                                     'TP_COR_RACA': 'COR/RAÇA',
                                     'TP_ST_CONCLUSAO': 'SITUAÇÃO DE CONCLUSÃO',
                                     'TP_ESCOLA': 'TIPO DE ESCOLA',
                                     'TP_LOCALIZACAO_ESC': 'LOCALIZAÇÃO DA ESCOLA',
                                     'TP_LINGUA': 'IDIOMA',
                                     'TP_STATUS_REDACAO': 'STATUS DA REDAÇÃO',
                                     'Q006': 'RENDA',
                                     'Q025': 'INTERNET',
                                     'NU_NOTA_CN': 'NOTA_CN', 'NU_NOTA_CH':'NOTA_CH', 'NU_NOTA_LC':'NOTA_LC', 'NU_NOTA_MT':'NOTA_MT',
                                     'NU_NOTA_COMP1':'NOTA_COMP1', 'NU_NOTA_COMP2':'NOTA_COMP2','NU_NOTA_COMP3':'NOTA_COMP3',
                                      'NU_NOTA_COMP4':'NOTA_COMP4', 'NU_NOTA_COMP5':'NOTA_COMP5', 'NU_NOTA_REDACAO':'NOTA_REDACAO'})

In [18]:
df_pe2019.columns

Index(['NU_INSCRICAO', 'FAIXA ETÁRIA', 'SEXO', 'COR/RAÇA',
       'SITUAÇÃO DE CONCLUSÃO', 'TIPO DE ESCOLA', 'IN_TREINEIRO',
       'NO_MUNICIPIO_ESC', 'LOCALIZAÇÃO DA ESCOLA', 'NO_MUNICIPIO_PROVA',
       'TP_PRESENCA_CN', 'TP_PRESENCA_CH', 'TP_PRESENCA_LC', 'TP_PRESENCA_MT',
       'NOTA_CN', 'NOTA_CH', 'NOTA_LC', 'NOTA_MT', 'IDIOMA',
       'STATUS DA REDAÇÃO', 'NOTA_COMP1', 'NOTA_COMP2', 'NOTA_COMP3',
       'NOTA_COMP4', 'NOTA_COMP5', 'NOTA_REDACAO', 'RENDA', 'INTERNET'],
      dtype='object')

### Separar entre vestibulandos e treineiros

> Filtrar apenas para os inscritos considerados vestibulandos e que não estão com o intuito de apenas treinar seus conhecimentos.

In [19]:
vestibulandos = df_pe2019.loc[df_pe2019.IN_TREINEIRO == 'Não']

### Calcular a presença total dos inscritos

> Filtrar apenas para os inscritos, considerados vestibulandos, que participaram dos dois dias de vestibular.

In [20]:
presenca_total = ['TP_PRESENCA_CN', 'TP_PRESENCA_CH', 'TP_PRESENCA_LC', 'TP_PRESENCA_MT']

In [21]:
vestibulandos['Presença Total'] = vestibulandos[presenca_total].sum(axis=1)

C:\Users\victo\AppData\Local\Temp/ipykernel_46712/3263105237.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  vestibulandos['Presença Total'] = vestibulandos[presenca_total].sum(axis=1)

In [22]:
vestibulandos_presentes = vestibulandos.loc[vestibulandos['Presença Total'] == 4]

In [23]:
vestibulandos_presentes['TP_PRESENCA_CN'].value_counts()

1    174100
0       169
2         2
Name: TP_PRESENCA_CN, dtype: int64

In [24]:
vestibulandos_presentes['TP_PRESENCA_CH'].value_counts()

1    174100
2       169
0         2
Name: TP_PRESENCA_CH, dtype: int64

In [25]:
vestibulandos_presentes['TP_PRESENCA_LC'].value_counts()

1    174100
2       169
0         2
Name: TP_PRESENCA_LC, dtype: int64

In [26]:
vestibulandos_presentes['TP_PRESENCA_MT'].value_counts()

1    174100
0       169
2         2
Name: TP_PRESENCA_MT, dtype: int64

### Separar os vestibulandos classificados

> Apenas nos interessa os vestibulandos que fizeram todas as provas nos dois dias que compareceram ao vestibular. Ou seja, aqueles que não tiveram nenhum tipo de erro.

In [27]:
vestibulandos_classificados_2019 = vestibulandos_presentes.loc[vestibulandos_presentes.TP_PRESENCA_MT == 1]

In [28]:
vestibulandos_classificados_2019.drop(columns=['IN_TREINEIRO','Presença Total'], inplace=True)

C:\Users\victo\anaconda3\lib\site-packages\pandas\core\frame.py:4906: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  return super().drop(

In [31]:
vestibulandos_classificados_2019.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 174100 entries, 43 to 5094992
Data columns (total 27 columns):
 #   Column                 Non-Null Count   Dtype
---  ------                 --------------   -----
 0   NU_INSCRICAO           174100 non-null  int64
 1   FAIXA ETÁRIA           174100 non-null  object
 2   SEXO                   174100 non-null  object
 3   COR/RAÇA               174100 non-null  object
 4   SITUAÇÃO DE CONCLUSÃO  174100 non-null  object
 5   TIPO DE ESCOLA         174100 non-null  object
 6   NO_MUNICIPIO_ESC       51574 non-null   object
 7   LOCALIZAÇÃO DA ESCOLA  51574 non-null   object
 8   NO_MUNICIPIO_PROVA     174100 non-null  object
 9   TP_PRESENCA_CN         174100 non-null  int64
 10  TP_PRESENCA_CH         174100 non-null  int64
 11  TP_PRESENCA_LC         174100 non-null  int64
 12  TP_PRESENCA_MT         174100 non-null  int64
 13  NOTA_CN                174100 non-null  float64
 14  NOTA_CH                174100 non-null  float64
 15  NOTA_LC                174100 non-null  float64
 16  NOTA_MT                174100 non-null  float64
 17  IDIOMA                 174100 non-null  object
 18  STATUS DA REDAÇÃO      174100 non-null  object
 19  NOTA_COMP1             174100 non-null  float64
 20  NOTA_COMP2             174100 non-null  float64
 21  NOTA_COMP3             174100 non-null  float64
 22  NOTA_COMP4             174100 non-null  float64
 23  NOTA_COMP5             174100 non-null  float64
 24  NOTA_REDACAO           174100 non-null  float64
 25  RENDA                  174100 non-null  object
 26  INTERNET               174100 non-null  object
dtypes: float64(10), int64(5), object(12)
memory usage: 37.2+ MB

In [32]:
vestibulandos_classificados_2019.isnull().sum()

NU_INSCRICAO                  0
FAIXA ETÁRIA                  0
SEXO                          0
COR/RAÇA                      0
SITUAÇÃO DE CONCLUSÃO         0
TIPO DE ESCOLA                0
NO_MUNICIPIO_ESC         122526
LOCALIZAÇÃO DA ESCOLA    122526
NO_MUNICIPIO_PROVA            0
TP_PRESENCA_CN                0
TP_PRESENCA_CH                0
TP_PRESENCA_LC                0
TP_PRESENCA_MT                0
NOTA_CN                       0
NOTA_CH                       0
NOTA_LC                       0
NOTA_MT                       0
IDIOMA                        0
STATUS DA REDAÇÃO             0
NOTA_COMP1                    0
NOTA_COMP2                    0
NOTA_COMP3                    0
NOTA_COMP4                    0
NOTA_COMP5                    0
NOTA_REDACAO                  0
RENDA                         0
INTERNET                      0
dtype: int64

### Preencher os valores ausentes dos nomes dos municípios e a localização da escola